In [ ]:
# Step 1: Upload CSV (run this and upload your file)
from google.colab import files
uploaded = files.upload()

Saving water_pollution_disease.csv to water_pollution_disease (1).csv


In [ ]:
# Step 2: Load libraries
import numpy as np
import pandas as pd

# Step 3: Read CSV
df = pd.read_csv('water_pollution_disease.csv')
print("Dataset Preview:\n", df.head())
print("Columns:\n", df.columns)

Dataset Preview:
      Country   Region  Year Water Source Type  Contaminant Level (ppm)  \
0     Mexico    North  2015              Lake                     6.06   
1     Brazil     West  2017              Well                     5.24   
2  Indonesia  Central  2022              Pond                     0.24   
3    Nigeria     East  2016              Well                     7.91   
4     Mexico    South  2005              Well                     0.12   

   pH Level  Turbidity (NTU)  Dissolved Oxygen (mg/L)  Nitrate Level (mg/L)  \
0      7.12             3.93                     4.28                  8.28   
1      7.84             4.79                     3.86                 15.74   
2      6.43             0.79                     3.42                 36.67   
3      6.71             1.96                     3.12                 36.92   
4      8.16             4.22                     9.15                 49.35   

   Lead Concentration (µg/L)  ...  Cholera Cases per 100,000 p

In [ ]:
# Extract relevant columns as NumPy arrays
# Replace 'Disease', 'Cases', 'Location' with actual column names from your CSV
diseases = df['Country'].to_numpy()  # Example: Replacing 'Disease' with 'Country'
cases = df['Year'].to_numpy()      # Example: Replacing 'Cases' with 'Year'
locations = df['Region'].to_numpy()   # Example: Replacing 'Location' with 'Region'

print("Diseases:", diseases[:5])
print("Cases:", cases[:5])
print("Locations:", locations[:5])

Diseases: ['Mexico' 'Brazil' 'Indonesia' 'Nigeria' 'Mexico']
Cases: [2015 2017 2022 2016 2005]
Locations: ['North' 'West' 'Central' 'East' 'South']


In [ ]:
cases = cases.astype(np.int32)

print("First case:", cases[0])
print("First 5 cases:", cases[:5])
print("Sliced cases [2:6]:", cases[2:6])

First case: 2015
First 5 cases: [2015 2017 2022 2016 2005]
Sliced cases [2:6]: [2022 2016 2005 2013]


In [ ]:
reshaped = cases[:12].reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Concatenate
new_data = np.array([10, 20, 30])
concat_cases = np.concatenate([cases[:3], new_data])
print("Concatenated:", concat_cases)

# Split
split_cases = np.array_split(cases[:10], 2)
print("Split arrays:", split_cases)

Reshaped (3x4):
 [[2015 2017 2022 2016]
 [2005 2013 2022 2024]
 [2014 2013 2023 2021]]
Concatenated: [2015 2017 2022   10   20   30]
Split arrays: [array([2015, 2017, 2022, 2016, 2005], dtype=int32), array([2013, 2022, 2024, 2014, 2013], dtype=int32)]


In [ ]:
print("Square root of cases:", np.sqrt(cases[:5]))
print("Sum of all cases:", np.sum(cases))
print("Average cases:", np.mean(cases))
print("Max cases:", np.max(cases))
print("Min cases:", np.min(cases))

Square root of cases: [44.88875137 44.91102315 44.96665431 44.89988864 44.77722635]
Sum of all cases: 6036038
Average cases: 2012.0126666666667
Max cases: 2024
Min cases: 2000


In [ ]:
increased_cases = cases + 5
print("Increased cases (broadcasted):", increased_cases[:5])

Increased cases (broadcasted): [2020 2022 2027 2021 2010]


In [ ]:
high_cases_mask = cases > 50
print("Boolean Mask (cases > 50):", high_cases_mask[:10])
print("Cases > 50:", cases[high_cases_mask])
print("Diseases with high cases:", diseases[high_cases_mask])

Boolean Mask (cases > 50): [ True  True  True  True  True  True  True  True  True  True]
Cases > 50: [2015 2017 2022 ... 2009 2009 2013]
Diseases with high cases: ['Mexico' 'Brazil' 'Indonesia' ... 'USA' 'Pakistan' 'Mexico']


In [ ]:
indices = [0, 3, 5]
print("Fancy Indexed cases:", cases[indices])
print("Corresponding diseases:", diseases[indices])

Fancy Indexed cases: [2015 2016 2013]
Corresponding diseases: ['Mexico' 'Nigeria' 'Ethiopia']


In [ ]:
sorted_cases = np.sort(cases)
print("Sorted cases:", sorted_cases[:10])

sort_indices = np.argsort(cases)
print("Indices that would sort the array:", sort_indices[:10])
print("Top 5 diseases by cases:", diseases[sort_indices[-5:]][::-1])

Sorted cases: [2000 2000 2000 2000 2000 2000 2000 2000 2000 2000]
Indices that would sort the array: [2983   21 2165   68 2951   77 2965 2964 2411 1465]
Top 5 diseases by cases: ['India' 'Mexico' 'USA' 'Pakistan' 'China']


In [ ]:
structured_array = np.array([
    (diseases[i], cases[i], locations[i])
    for i in range(len(cases))
], dtype=[('Disease', 'U30'), ('Cases', 'i4'), ('Location', 'U30')])

print("Structured array example:\n", structured_array[:5])
print("Access disease from first row:", structured_array[0]['Disease'])

Structured array example:
 [('Mexico', 2015, 'North') ('Brazil', 2017, 'West')
 ('Indonesia', 2022, 'Central') ('Nigeria', 2016, 'East')
 ('Mexico', 2005, 'South')]
Access disease from first row: Mexico
